/* Run in an isolated browser context. Collector responses are protocol fixtures. */
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const results = [], captured = [];
const check = (name, value) => { assert.ok(value, name); results.push({test:name,pass:true}); };
const grant = {analytics:'granted',advertising:'granted',email_marketing:'unknown',sms_marketing:'denied',source:'test_cmp'};
const config = {site_id:'site_fixture',installation_id:'install_fixture',environment:'test',endpoint:'https://collector.example/events',origin:'https://shop.example.co.th',plugin_version:'3.0.0-alpha.1',policy_version:'1',page_id:'42',product_id:'42',entry_type:'product',classification_version:'1',storefront:'th-TH',served_version:null};
(async () => {
  const browser = await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE ? {executablePath:process.env.CHROME_EXECUTABLE} : {})});
  try {
    const context = await browser.newContext(); let mode = 'accepted';
    await context.route('**/*',async route => {
      const request=route.request(); const url=request.url();
      if (url.startsWith('https://collector.example/')) {
        if (request.method()==='OPTIONS') return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':config.origin,'Access-Control-Allow-Headers':'content-type'}});
        const data=request.postDataJSON(); captured.push(...data.events);
        return route.fulfill({status:202,headers:{'Access-Control-Allow-Origin':config.origin},contentType:'application/json',body:JSON.stringify({results:data.events.map(e=>({event_id:e.event_id,body_hash:mode==='wrong_hash' ? '0'.repeat(64):crypto.createHash('sha256').update(JSON.stringify(e)).digest('hex'),status:'accepted',receipt_id:'receipt_'+e.event_id,received_at:new Date().toISOString(),code:null}))})});
      }
      if (url.endsWith('/pixel.js')) return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(root+'/magellan-for-woocommerce/assets/magellan-v3-pixel.js','utf8')});
      if (url.endsWith('/checkout.js')) return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(root+'/magellan-for-woocommerce/assets/magellan-v3-checkout.js','utf8')});
      return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><title>Magellan isolated fixture</title></head><body><button data-magellan-component="hero" data-magellan-action="shop">Shop</button><form class="checkout"></form><script>window.MagellanV3Config='+JSON.stringify(config)+'</script><script src="/pixel.js"></script><script src="/checkout.js"></script></body></html>'});
    });
    const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    await page.goto(config.origin+'/flowers/?utm_source=google&utm_medium=organic&gclid=synthetic_click&email=private@example.com');
    check('unknown consent makes no collector request',captured.length===0);
    check('unknown consent creates no visitor cookie',!(await context.cookies()).some(c=>c.name==='_mgln_v3_visitor_site_fixture'));
    await page.evaluate(g=>window.MagellanV3.setConsent(g),grant);
    await page.evaluate(()=>window.MagellanV3.flush());
    check('consented page/product/checkout events captured',['page_viewed','product_viewed','checkout_started'].every(t=>captured.some(e=>e.event_type===t)));
    const first=captured.find(e=>e.event_type==='page_viewed');
    check('query strings excluded from page identity',first.payload.path==='/flowers/' && !JSON.stringify(first).includes('private@example.com'));
    check('acknowledged browser queue cleared',await page.evaluate(()=>JSON.parse(localStorage.getItem('magellan:v3:site_fixture:queue')).length===0));
    const cookies=await context.cookies(); const visitor=cookies.find(c=>c.name==='_mgln_v3_visitor_site_fixture');
    check('host-only secure cookie on co.th',visitor.domain==='shop.example.co.th'&&visitor.secure&&visitor.sameSite==='Lax');
    await context.addInitScript(g=>window.MagellanConsent=g,grant);
    await page.goto(config.origin+'/second/?utm_source=facebook&utm_medium=cpc');
    await page.evaluate(()=>new Promise(resolve=>window.MagellanV3.whenReady(resolve)));
    await page.evaluate(()=>window.MagellanV3.flush());
    const second=captured.filter(e=>e.event_type==='page_viewed').at(-1);
    check('navigation retains visitor and session',second.visitor_id===first.visitor_id&&second.session_id===first.session_id);
    check('entry origin stays frozen, later source retained',second.payload.entry.source_evidence.utm.source==='google'&&second.payload.source_evidence.utm.source==='facebook');
    const other=await context.newPage(); await other.goto(config.origin+'/other');
    await other.evaluate(()=>new Promise(resolve=>window.MagellanV3.whenReady(resolve)));
    await other.evaluate(()=>window.MagellanV3.flush());
    check('second tab shares session',captured.filter(e=>e.event_type==='page_viewed').at(-1).session_id===first.session_id);
    mode='wrong_hash';
    await Promise.all([page.evaluate(()=>{window.MagellanV3.registerInteraction('tab-one');window.MagellanV3.interaction('tab-one','click');}),other.evaluate(()=>{window.MagellanV3.registerInteraction('tab-two');window.MagellanV3.interaction('tab-two','click');})]);
    await Promise.all([page.evaluate(()=>window.MagellanV3.flush()),other.evaluate(()=>window.MagellanV3.flush())]);
    check('concurrent tabs retain both unacknowledged events',await page.evaluate(()=>{const q=JSON.parse(localStorage.getItem('magellan:v3:site_fixture:queue'));return ['tab-one','tab-two'].every(id=>q.some(e=>e.payload.component_id===id));}));
    mode='accepted'; await page.evaluate(()=>window.MagellanV3.flush()); await other.evaluate(()=>window.MagellanV3.flush());
    const n=captured.length;
    await page.evaluate(()=>{window.MagellanV3.interaction('unregistered','click');window.MagellanV3.registerInteraction('hero');window.MagellanV3.interaction('hero','shop');});
    await page.evaluate(()=>window.MagellanV3.flush());
    check('only registered interactions emitted',captured.slice(n).filter(e=>e.event_type==='interaction_observed').length===1);
    mode='wrong_hash';
    await page.evaluate(()=>window.MagellanV3.interaction('hero','shop')); await page.evaluate(()=>window.MagellanV3.flush());
    check('wrong receipt hash retains browser event',await page.evaluate(()=>JSON.parse(localStorage.getItem('magellan:v3:site_fixture:queue')).length>0));
    await page.evaluate(()=>window.MagellanV3.setConsent({analytics:'denied',source:'test_cmp'}));
    await other.waitForFunction(()=>localStorage.getItem('magellan:v3:site_fixture:queue')===null);
    const atRevoke=captured.length;
    await other.evaluate(()=>{window.MagellanV3.registerInteraction('hero');window.MagellanV3.interaction('hero','shop');});
    await other.evaluate(()=>window.MagellanV3.flush());
    check('withdrawal stops collection in the second tab',!captured.slice(atRevoke).some(e=>e.event_type==='interaction_observed'));
    await other.close();
    check('withdrawal clears identifiers and persisted queue',!(await context.cookies()).some(c=>c.name==='_mgln_v3_visitor_site_fixture')&&await page.evaluate(()=>localStorage.getItem('magellan:v3:site_fixture:queue')===null));
    mode='accepted'; await page.evaluate(g=>window.MagellanV3.setConsent(g),grant); await page.evaluate(()=>window.MagellanV3.flush());
    await page.waitForFunction(()=>JSON.parse(localStorage.getItem('magellan:v3:site_fixture:queue') || '[]').length===0);
    check('new consent does not resurrect erased visitor',captured.filter(e=>e.event_type==='page_viewed').at(-1).visitor_id!==first.visitor_id);
    await page.evaluate(g=>{Object.defineProperty(navigator,'globalPrivacyControl',{value:true,configurable:true});return window.MagellanV3.setConsent(g);},grant);
    await page.evaluate(()=>{window.MagellanV3.registerInteraction('hero');window.MagellanV3.interaction('hero','shop');}); await page.evaluate(()=>window.MagellanV3.flush());
    check('GPC prevents advertising grant',captured.at(-1).consent.gpc===true&&captured.at(-1).consent.advertising==='denied');
    check('advertising withdrawal removes saved raw click identifiers',await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('magellan:v3:site_fixture:session')).entry.source_evidence.click_ids).length===0));
    const oldVisitor=captured.filter(e=>e.event_type==='page_viewed').at(-1).visitor_id;
    await context.clearCookies();
    await page.evaluate(()=>window.MagellanV3.interaction('hero','shop')); await page.evaluate(()=>window.MagellanV3.flush());
    check('cleared cookies cannot resurrect the old visitor',captured.at(-1).visitor_id!==oldVisitor);
    check('no browser exceptions',errors.length===0);
    const blocked=await context.newPage();
    await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked')}});});
    await blocked.goto(config.origin+'/blocked');
    await blocked.evaluate(()=>new Promise(resolve=>window.MagellanV3.whenReady(resolve)));
    await blocked.evaluate(()=>window.MagellanV3.flush());
    check('blocked storage reports page-local continuity',captured.filter(e=>e.event_type==='page_viewed').at(-1).payload.continuity==='page_local');
    await blocked.close();
    fs.writeFileSync(root+'/tests/browser-events.json',JSON.stringify(captured,null,2)+'\n');
    fs.writeFileSync(root+'/tests/browser-results.json',JSON.stringify({browser:browser.version(),transport:'intercepted collector responses; real isolated Chrome context',results},null,2)+'\n');
    console.log(results.length+' browser checks passed');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
